#!/bin/bash

cd "$(git rev-parse --show-toplevel)"

printf "\nValidating PHP files:\n"

TLINT="vendor/bin/tlint"

if [[ ! -x "$TLINT" ]]; then
  printf "\033[41m\033[30mPlease install tlint\033[0m (composer install)\n"
  exit 1
fi

STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$"))
echo "TLint'ing ${#STAGED_FILES[@]} files"

PASS=true

for FILE in ${STAGED_FILES[@]}
do
  $TLINT lint "$FILE"

  if [[ "$?" == 0 ]]; then
    printf "\t\033[32mTLint Passed: $FILE\033[0m"
  else
    printf "\t\033[31mTLint Failed: $FILE\033[0m"
    PASS=false
  fi
done

if [[ "${PASS}" == false ]]; then
  printf "\n\t\033[41m\033[30mCOMMIT FAILED:\033[0m Fix tlint errors and try again\n"
  exit 1
fi

#### ESLINT
printf "\nValidating Javascript:\n"

ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"
# Check for eslint
if [[ ! -x "$ESLINT" ]]; then
  printf "\t\033[41mPlease install ESlint\033[0m (npm i --save-dev eslint)"
  exit 1
fi


STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".js\{0,1\}$")

PASS=true

for FILE in ${STAGED_FILES[@]}
do
  "$ESLINT" "$FILE"

  if [[ "$?" == 0 ]]; then
    printf "\t\033[32mESLint Passed: $FILE\033[0m"
  else
    printf "\t\033[31mESLint Failed: $FILE\033[0m"
    PASS=false
  fi
done

if [[ "${PASS}" == false ]]; then
  printf "\n\t\033[41m\033[30mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
  exit 1
fi


#### SUCCESS
printf "\n\t\033[42m\033[30mCOMMIT SUCCEEDED\033[0m\n"
exit $?

